syntax = "proto3";

package auth;

option go_package = "github.com/voznikaetnepriyazn/Autorization-servise";

service Auth {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc IsAdmin (IsAdminRequest) returns (IsAdminResponse);
    rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
}

message RegisterRequest {
    string email = 1;
    string password = 2;
}

message RegisterResponse {
    bytes user_id = 1;
}

message LoginRequest {
    string email = 1;
    string password = 2;
    int32 app_id = 3;
}

message LoginResponse {
    string token = 1;
    string user_id = 2;
    string role = 3;
}

message IsAdminRequest {
    bytes user_id = 1;
}

message IsAdminResponse {
    bool is_admin = 1;
}

message ValidateTokenRequest {
    string token = 1;
}

message ValidateTokenResponse {
    string user_id = 1;
    string email = 2;  
    string role = 3;
}

